### ISSUE TITLE
Did you get this to work?

### ISSUE THREAD

**Issue by fbsdmon** [chris-smith-zocdoc/packer-windows-example#1]
Did you manage to get a working packer-winrm setup with raw module?

**Comment by chris-smith-zocdoc** [comment]
Yes I just pushed a [commit](https://github.com/chris-smith-zocdoc/packer-windows-example/commit/f50ae58fd882754cda9426951b5bdb58d50ddbca) demonstrating this

**Comment by fbsdmon** [comment]
Can you try if this works for you:
```
    - name: Disable Firewall
      raw: Set-NetFirewallProfile -Enabled False
```
I can't seem to execute native powershell commands
